# highlighter: pygments
# markdown: rdiscount
# rdiscount:
#   extensions: [smart]
# permalink: /:title.html
# paginate: 5
# gems: [jekyll-paginate]
# port: 4000
# safe: true
# url: http://imkaywu.github.io/cv
# author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /cv/
title: Kai Wu's Resume
name: Kai Wu
email: kaywu@ece.ubc.ca
email_full: mailto:kaywu@ece.ubc.ca
website: imkaywu.github.io
website_full: https://imkaywu.github.io
github: imkaywu
twitter: _BlacKay_
tel: +1 6047161058
tel_full: tel:+16047161058
# google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address: 6608 Maple Street
postcode: V6P 5P3
city: Vancouver
country: Canada
# google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
